#!/usr/bin/env python3
"""Hero/teaser figure for the very front of the paper: composites the
archetype-verdict-recovery forest plot (top) with the runtime and
accuracy scaling benchmarks (bottom), so the headline empirical result --
PCI matches actual-causality verdicts, and stays tractable long past where
exact enumeration gives out -- is visible on page one.

This does not recompute anything: it composites the existing source PNGs
(already generated by their own notebooks) into one panel figure with
consistent panel labels, matching the paper's figure style.

Run: python3 scripts/make_hero_figure.py
Output: figures/hero_verdicts_and_scaling.{pdf,png}
"""
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image

INK = "#1d2730"
CAP_COL = "#6b7780"

plt.rcParams.update({"font.family": "DejaVu Sans", "pdf.fonttype": 42,
                     "ps.fonttype": 42})

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ARCHETYPES = os.path.join(HERE, "figures", "archetypes_threshold_forest.png")
RUNTIME = os.path.join(HERE, "docs/source/ac_benchmark/plot1_runtime.png")
ACCURACY = os.path.join(HERE, "docs/source/ac_benchmark/plot3_accuracy.png")


def trimmed(path, pad=12):
    """Crop a source PNG to its true (near-white) content bounding box, so
    composited panels don't carry each source figure's own margins."""
    im = Image.open(path).convert("RGB")
    arr = np.asarray(im)
    mask = (arr < 250).any(axis=2)  # non-white pixels
    rows = np.where(mask.any(axis=1))[0]
    cols = np.where(mask.any(axis=0))[0]
    top, bot = max(rows[0] - pad, 0), min(rows[-1] + pad, arr.shape[0])
    left, right = max(cols[0] - pad, 0), min(cols[-1] + pad, arr.shape[1])
    return np.asarray(im.crop((left, top, right, bot)))


def panel(ax, img, label, title):
    ax.imshow(img)
    ax.axis("off")
    ax.set_title(f"{label}  {title}", loc="left", fontsize=11,
                 fontweight="bold", color=INK, pad=8)


def emit(outdir):
    top_img = trimmed(ARCHETYPES)
    bl_img = trimmed(RUNTIME)
    br_img = trimmed(ACCURACY)
    top_aspect = top_img.shape[0] / top_img.shape[1]   # h/w
    bl_aspect = bl_img.shape[0] / bl_img.shape[1]
    br_aspect = br_img.shape[0] / br_img.shape[1]

    W = 9.0  # content width, inches
    top_h = W * top_aspect
    bot_h = (W / 2) * max(bl_aspect, br_aspect)

    fig = plt.figure(figsize=(W, top_h + bot_h + 1.1))
    gs = fig.add_gridspec(2, 2, height_ratios=[top_h, bot_h],
                          hspace=0.38, wspace=0.22)

    ax_top = fig.add_subplot(gs[0, :])
    panel(ax_top, top_img, "(a)",
          "PCI matches actual-causality verdicts on all ten archetype checks")

    ax_bl = fig.add_subplot(gs[1, 0])
    panel(ax_bl, bl_img, "(b)", "Runtime past exact AC's cutoff")

    ax_br = fig.add_subplot(gs[1, 1])
    panel(ax_br, br_img, "(c)", "Accuracy past exact AC's cutoff")

    fig.savefig(os.path.join(outdir, "hero_verdicts_and_scaling.pdf"),
               dpi=400, bbox_inches="tight", facecolor="white")
    fig.savefig(os.path.join(outdir, "hero_verdicts_and_scaling.png"),
               dpi=200, bbox_inches="tight", facecolor="white")
    plt.close(fig)
    print("wrote hero_verdicts_and_scaling.{pdf,png} to", outdir)


if __name__ == "__main__":
    outdir = os.path.join(HERE, "figures")
    os.makedirs(outdir, exist_ok=True)
    emit(outdir)
